title: Dave Carlson # your name (or website title) here
logo: "https://avatars1.githubusercontent.com/u/1476951"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Solutions Architect @ <a href="https://databricks.com/">Databricks</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/david-carlson/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
